import { defineConfig } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
import nimbus, { defineConfig as defineNimbusConfig } from "@cloudflare/nimbus-docs";
import { tableScroll } from "@cloudflare/nimbus-docs/markdown";
import mkdocsHeadingIds from "./src/lib/mkdocs-heading-ids.mjs";
import { DEPRECATED, googleAnalytics, STABLE_VERSION } from "./src/lib/site.mjs";
import { redirects, sidebars, versions } from "./src/versions.generated.mjs";

const nimbusConfig = defineNimbusConfig({
  site: "https://docs.phalcon.io",
  title: "Phalcon Documentation",
  description:
    "Phalcon Framework. A full-stack PHP framework delivered as a PHP extension, offering lower resource consumption and high performance.",
  locale: "en",
  github: "https://github.com/phalcon/documentation",
  socialImageAlt: "Phalcon documentation preview",
  // Google Analytics; an empty id disables it.
  head: googleAnalytics("G-JR4REKBKH3") as { tag: "script"; attrs?: Record<string, string>; content?: string }[],
  // Every published version is a `docs-<version>` collection listed in
  // `others`. The primary `docs` collection stays empty; `current` is only
  // the label for it. `deprecated` adds the deprecation banner, the sidebar
  // badge and the Pagefind `status:deprecated` facet.
  versions: {
    current: "latest",
    others: versions,
    deprecated: DEPRECATED,
  },
  // Each version route builds its own rail from src/sidebar/<version>.mjs
  // (generated by resources/nimbus/convert.py from that version's
  // mkdocs.yml). This global config is the newest version's navigation and
  // serves nimbus's own helpers (breadcrumbs, llms.txt).
  sidebar: {
    items: (sidebars as Record<string, unknown>)[versions[0]] as typeof sidebars[keyof typeof sidebars],
    scope: "full",
    defaultCollapsed: true,
  },
});

export default defineConfig({
  output: "static",
  // The primary collection holds no documentation: the root sends readers
  // to the stable version, as the MkDocs site did. Each version brings the
  // redirects of its MkDocs stubs (generated by resources/nimbus/convert.py).
  redirects: {
    "/": `/${STABLE_VERSION}/introduction/`,
    ...redirects,
  },
  // Tailwind v4 via its Vite plugin (the integration Astro recommends for
  // Tailwind v4 — replaces the PostCSS plugin, which doesn't build under
  // Astro 7's Vite 8 bundler).
  vite: {
    plugins: [tailwindcss()],
  },
  // Hover-prefetch link targets so full-page navigations feel instant without
  // a client-side router.
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "hover",
  },
  integrations: [
    nimbus(nimbusConfig, {
      // Authoring rules are opt-in by design — your repo, your taste. The
      // two below are the load-bearing pair: frontmatter has to validate
      // against the content schema for the page to render properly, and
      // broken internal links are 404s for your readers. Add the others
      // (heading hierarchy, code-block language, style, etc.) when you're
      // ready to enforce them — see `nimbus-docs lint --help`.
      rules: {
        "nimbus/frontmatter-shape": "error",
        "nimbus/internal-link": "error",
      },
      // Wrap wide tables so they scroll instead of overflowing the page
      // (styled by `.nb-table-scroll` in src/styles/prose.css).
      markdown: {
        // Heading ids as MkDocs generated them, so that old anchors keep
        // working.
        hastPlugins: [tableScroll(), mkdocsHeadingIds()],
      },
    }),
  ],
});
