// Generated by resources/nimbus/convert.py from the mkdocs.yml nav of version 3.4. Do not edit.
export default [
  {
    "label": "Home",
    "collapsed": true,
    "items": [
      {
        "label": "Introduction",
        "link": "/3.4/introduction/"
      },
      {
        "label": "Changelog",
        "collapsed": true,
        "items": [
          {
            "label": "Current Version",
            "link": "https://github.com/phalcon/cphalcon/blob/5.0.x/CHANGELOG-5.0.md"
          },
          {
            "label": "Releases",
            "link": "/3.4/releases/"
          },
          {
            "label": "How to upgrade",
            "link": "/3.4/upgrade/"
          }
        ]
      },
      {
        "label": "Contributing",
        "collapsed": true,
        "items": [
          {
            "label": "Contributions",
            "link": "/3.4/contributions/"
          },
          {
            "label": "Asking a question",
            "link": "https://phalcon.io/discussions"
          },
          {
            "label": "Requesting a change",
            "link": "/3.4/new-feature-request/"
          },
          {
            "label": "Issuing a Pull Request",
            "link": "/3.4/new-pull-request/"
          }
        ]
      },
      {
        "label": "Guides",
        "collapsed": true,
        "items": [
          {
            "label": "Backtrace Generation",
            "link": "/3.4/generating-backtrace/"
          },
          {
            "label": "Reproducible Tests",
            "link": "/3.4/reproducible-tests/"
          },
          {
            "label": "Testing environment",
            "link": "/3.4/testing-environment/"
          },
          {
            "label": "Coding Standard",
            "link": "/3.4/coding-standard/"
          }
        ]
      },
      {
        "label": "Sponsoring",
        "link": "/3.4/sponsors/"
      }
    ]
  },
  {
    "label": "Getting Started",
    "collapsed": true,
    "items": [
      {
        "label": "Installation",
        "link": "/3.4/installation/"
      },
      {
        "label": "Webserver Setup",
        "link": "/3.4/webserver-setup/"
      },
      {
        "label": "WAMP",
        "link": "/3.4/webserver-wamp/"
      },
      {
        "label": "XAMPP",
        "link": "/3.4/webserver-xampp/"
      },
      {
        "label": "Environments",
        "collapsed": true,
        "items": [
          {
            "label": "Nanobox",
            "link": "/3.4/environments-nanobox/"
          }
        ]
      },
      {
        "label": "Development Tools",
        "collapsed": true,
        "items": [
          {
            "label": "Installation",
            "link": "/3.4/devtools-installation/"
          },
          {
            "label": "Usage",
            "link": "/3.4/devtools-usage/"
          },
          {
            "label": "Debug",
            "link": "/3.4/debug/"
          }
        ]
      },
      {
        "label": "Tutorials",
        "collapsed": true,
        "items": [
          {
            "label": "Basic",
            "link": "/3.4/tutorial-basic/"
          },
          {
            "label": "Invo",
            "link": "/3.4/tutorial-invo/"
          },
          {
            "label": "REST",
            "link": "/3.4/tutorial-rest/"
          },
          {
            "label": "Vokuro",
            "link": "/3.4/tutorial-vokuro/"
          },
          {
            "label": "Performance",
            "link": "/3.4/performance/"
          }
        ]
      }
    ]
  },
  {
    "label": "Core",
    "collapsed": true,
    "items": [
      {
        "label": "Application",
        "link": "/3.4/application/"
      },
      {
        "label": "Micro",
        "link": "/3.4/application-micro/"
      },
      {
        "label": "CLI",
        "link": "/3.4/application-cli/"
      },
      {
        "label": "DI Container",
        "link": "/3.4/di/"
      },
      {
        "label": "MVC",
        "link": "/3.4/mvc/"
      },
      {
        "label": "Namespaces",
        "link": "/3.4/namespaces/"
      }
    ]
  },
  {
    "label": "Database",
    "collapsed": true,
    "items": [
      {
        "label": "Layer",
        "link": "/3.4/db-layer/"
      },
      {
        "label": "PHQL",
        "link": "/3.4/db-phql/"
      },
      {
        "label": "ODM",
        "link": "/3.4/db-odm/"
      },
      {
        "label": "Models",
        "link": "/3.4/db-models/"
      },
      {
        "label": "Behaviors",
        "link": "/3.4/db-models-behaviors/"
      },
      {
        "label": "Cache",
        "link": "/3.4/db-models-cache/"
      },
      {
        "label": "Events",
        "link": "/3.4/db-models-events/"
      },
      {
        "label": "Metadata",
        "link": "/3.4/db-models-metadata/"
      },
      {
        "label": "Relationships",
        "link": "/3.4/db-models-relationships/"
      },
      {
        "label": "Transactions",
        "link": "/3.4/db-models-transactions/"
      },
      {
        "label": "Validators",
        "link": "/3.4/db-models-validation/"
      },
      "db-pagination",
      {
        "label": "Migrations",
        "link": "/3.4/db-migrations/"
      }
    ]
  },
  {
    "label": "Front End",
    "collapsed": true,
    "items": [
      {
        "label": "Assets",
        "link": "/3.4/assets/"
      },
      {
        "label": "Flash Messenger",
        "link": "/3.4/flash/"
      },
      "forms",
      {
        "label": "Image",
        "link": "/3.4/image/"
      },
      {
        "label": "Tag",
        "link": "/3.4/tag/"
      },
      {
        "label": "View",
        "link": "/3.4/views/"
      },
      {
        "label": "Volt",
        "link": "/3.4/volt/"
      }
    ]
  },
  {
    "label": "Business Logic",
    "collapsed": true,
    "items": [
      {
        "label": "Access Control Lists",
        "link": "/3.4/acl/"
      },
      {
        "label": "Annotations",
        "link": "/3.4/annotations/"
      },
      {
        "label": "Controllers",
        "link": "/3.4/controllers/"
      },
      {
        "label": "Dispatcher",
        "link": "/3.4/dispatcher/"
      },
      {
        "label": "Event Manager",
        "link": "/3.4/events/"
      },
      {
        "label": "Filters",
        "link": "/3.4/filter/"
      },
      "routing",
      {
        "label": "Sessions",
        "link": "/3.4/session/"
      },
      {
        "label": "Url",
        "link": "/3.4/url/"
      },
      "validation"
    ]
  },
  {
    "label": "Services",
    "collapsed": true,
    "items": [
      {
        "label": "Cache",
        "link": "/3.4/cache/"
      },
      {
        "label": "Config",
        "link": "/3.4/config/"
      },
      {
        "label": "Escaper",
        "link": "/3.4/escaper/"
      },
      {
        "label": "Loader",
        "link": "/3.4/loader/"
      },
      {
        "label": "Logger",
        "link": "/3.4/logging/"
      },
      {
        "label": "HTTP",
        "collapsed": true,
        "items": [
          {
            "label": "Cookies",
            "link": "/3.4/cookies/"
          },
          {
            "label": "Request",
            "link": "/3.4/request/"
          },
          {
            "label": "Response",
            "link": "/3.4/response/"
          }
        ]
      },
      {
        "label": "i18n",
        "collapsed": true,
        "items": [
          "i18n",
          {
            "label": "Translate",
            "link": "/3.4/translate/"
          }
        ]
      },
      {
        "label": "Queue",
        "link": "/3.4/queue/"
      },
      {
        "label": "Security",
        "collapsed": true,
        "items": [
          {
            "label": "Cryptography",
            "link": "/3.4/crypt/"
          },
          "security"
        ]
      }
    ]
  },
  {
    "label": "Discussions",
    "link": "https://github.com/orgs/phalcon/discussions"
  },
  {
    "label": "Discussions(v6)",
    "link": "https://github.com/phalcon/phalcon/discussions"
  },
  {
    "label": "Blog",
    "link": "https://blog.phalcon.io/"
  }
];
