// Generated by resources/nimbus/convert.py from the mkdocs.yml nav of version 4.2. Do not edit.
export default [
  {
    "label": "Home",
    "collapsed": true,
    "items": [
      {
        "label": "Introduction",
        "link": "/4.2/introduction/"
      },
      {
        "label": "Changelog",
        "collapsed": true,
        "items": [
          {
            "label": "Current Version",
            "link": "https://github.com/phalcon/cphalcon/blob/5.0.x/CHANGELOG-5.0.md"
          },
          {
            "label": "Releases",
            "link": "/4.2/releases/"
          },
          {
            "label": "How to upgrade",
            "link": "/4.2/upgrade/"
          }
        ]
      },
      {
        "label": "Contributing",
        "collapsed": true,
        "items": [
          "contributions",
          {
            "label": "Asking a question",
            "link": "https://phalcon.io/discussions"
          },
          {
            "label": "Requesting a change",
            "link": "/4.2/new-feature-request/"
          },
          {
            "label": "Issuing a Pull Request",
            "link": "/4.2/new-pull-request/"
          }
        ]
      },
      {
        "label": "Guides",
        "collapsed": true,
        "items": [
          {
            "label": "Backtrace Generation",
            "link": "/4.2/generating-backtrace/"
          },
          "reproducible-tests",
          {
            "label": "Testing environment",
            "link": "/4.2/testing-environment/"
          },
          {
            "label": "Coding Standard",
            "link": "/4.2/coding-standard/"
          }
        ]
      },
      {
        "label": "Sponsoring",
        "link": "/4.2/sponsors/"
      }
    ]
  },
  {
    "label": "Getting Started",
    "collapsed": true,
    "items": [
      "installation",
      "webserver-setup",
      {
        "label": "Environments",
        "collapsed": true,
        "items": [
          {
            "label": "Devilbox",
            "link": "/4.2/environments-devilbox/"
          },
          {
            "label": "Nanobox",
            "link": "/4.2/environments-nanobox/"
          }
        ]
      },
      {
        "label": "Development Tools",
        "collapsed": true,
        "items": [
          {
            "label": "Devtools",
            "link": "/4.2/devtools/"
          },
          {
            "label": "Debug",
            "link": "/4.2/support-debug/"
          },
          {
            "label": "Migrations",
            "link": "/4.2/db-migrations/"
          },
          "unit-testing"
        ]
      },
      {
        "label": "Tutorials",
        "collapsed": true,
        "items": [
          {
            "label": "Basic",
            "link": "/4.2/tutorial-basic/"
          },
          {
            "label": "Invo",
            "link": "/4.2/tutorial-invo/"
          },
          {
            "label": "REST",
            "link": "/4.2/tutorial-rest/"
          },
          {
            "label": "Vokuro",
            "link": "/4.2/tutorial-vokuro/"
          },
          {
            "label": "Use case",
            "link": "/4.2/use-case/"
          },
          "performance"
        ]
      }
    ]
  },
  {
    "label": "Core",
    "collapsed": true,
    "items": [
      "application",
      {
        "label": "Micro",
        "link": "/4.2/application-micro/"
      },
      {
        "label": "CLI",
        "link": "/4.2/application-cli/"
      },
      {
        "label": "DI Container",
        "link": "/4.2/di/"
      },
      {
        "label": "MVC",
        "link": "/4.2/mvc/"
      },
      "namespaces"
    ]
  },
  {
    "label": "Database",
    "collapsed": true,
    "items": [
      {
        "label": "Layer",
        "link": "/4.2/db-layer/"
      },
      {
        "label": "PHQL",
        "link": "/4.2/db-phql/"
      },
      {
        "label": "ODM",
        "link": "/4.2/db-odm/"
      },
      "db-models",
      {
        "label": "Behaviors",
        "link": "/4.2/db-models-behaviors/"
      },
      {
        "label": "Cache",
        "link": "/4.2/db-models-cache/"
      },
      {
        "label": "Events",
        "link": "/4.2/db-models-events/"
      },
      {
        "label": "Metadata",
        "link": "/4.2/db-models-metadata/"
      },
      {
        "label": "Relationships",
        "link": "/4.2/db-models-relationships/"
      },
      {
        "label": "Transactions",
        "link": "/4.2/db-models-transactions/"
      },
      {
        "label": "Validators",
        "link": "/4.2/db-models-validation/"
      },
      "pagination",
      {
        "label": "Migrations",
        "link": "/4.2/db-migrations/"
      }
    ]
  },
  {
    "label": "Front End",
    "collapsed": true,
    "items": [
      {
        "label": "Assets",
        "link": "/4.2/assets/"
      },
      {
        "label": "Flash Messenger",
        "link": "/4.2/flash/"
      },
      "forms",
      "image",
      {
        "label": "Tag",
        "link": "/4.2/tag/"
      },
      {
        "label": "View",
        "link": "/4.2/views/"
      },
      {
        "label": "Volt",
        "link": "/4.2/volt/"
      }
    ]
  },
  {
    "label": "Business Logic",
    "collapsed": true,
    "items": [
      {
        "label": "Access Control Lists",
        "link": "/4.2/acl/"
      },
      "annotations",
      "controllers",
      {
        "label": "Dispatcher",
        "link": "/4.2/dispatcher/"
      },
      {
        "label": "Event Manager",
        "link": "/4.2/events/"
      },
      {
        "label": "Filters",
        "link": "/4.2/filter/"
      },
      {
        "label": "Routing",
        "link": "/4.2/routing/"
      },
      {
        "label": "Sessions",
        "link": "/4.2/session/"
      },
      {
        "label": "Url",
        "link": "/4.2/url/"
      },
      {
        "label": "Validation",
        "link": "/4.2/validation/"
      }
    ]
  },
  {
    "label": "Services",
    "collapsed": true,
    "items": [
      "cache",
      {
        "label": "Config",
        "link": "/4.2/config/"
      },
      "escaper",
      {
        "label": "HTTP",
        "collapsed": true,
        "items": [
          {
            "label": "Cookies",
            "link": "response/#cookies"
          },
          {
            "label": "Request",
            "link": "/4.2/request/"
          },
          {
            "label": "Response",
            "link": "/4.2/response/"
          }
        ]
      },
      "loader",
      "logger",
      {
        "label": "i18n",
        "collapsed": true,
        "items": [
          "i18n",
          {
            "label": "Translate",
            "link": "/4.2/translate/"
          }
        ]
      },
      {
        "label": "Queue",
        "link": "/4.2/queue/"
      },
      {
        "label": "PSR",
        "collapsed": true,
        "items": [
          {
            "label": "PSR-3 Logger",
            "link": "/4.2/logger/"
          },
          {
            "label": "PSR-0, PSR-4 Loader",
            "link": "/4.2/loader/"
          },
          {
            "label": "PSR-7 HTTP Request",
            "link": "http-request.md"
          },
          {
            "label": "PSR-7 HTTP Response",
            "link": "http-response.md"
          },
          {
            "label": "PSR-7 HTTP Server Request",
            "link": "http-server-request.md"
          },
          {
            "label": "PSR-7 HTTP Stream",
            "link": "http-stream.md"
          },
          {
            "label": "PSR-7 HTTP UploadedFile",
            "link": "http-uploaded-file.md"
          },
          {
            "label": "PSR-7 HTTP Uri",
            "link": "http-uri.md"
          },
          {
            "label": "PSR-11 Container",
            "link": "/4.2/container/"
          },
          {
            "label": "PSR-13 HTML Links",
            "link": "/4.2/html-link/"
          },
          {
            "label": "PSR-17 HTTP Factories",
            "link": "http-factories.md"
          }
        ]
      },
      {
        "label": "Security",
        "collapsed": true,
        "items": [
          {
            "label": "Cryptography",
            "link": "/4.2/crypt/"
          },
          "security",
          {
            "label": "JWT",
            "link": "/4.2/security-jwt/"
          }
        ]
      },
      {
        "label": "Utility",
        "collapsed": true,
        "items": [
          "collection",
          "domain",
          {
            "label": "Helper",
            "link": "/4.2/helper/"
          },
          {
            "label": "Registry",
            "link": "/4.2/registry/"
          }
        ]
      }
    ]
  },
  {
    "label": "Discussions",
    "link": "https://github.com/orgs/phalcon/discussions"
  },
  {
    "label": "Discussions(v6)",
    "link": "https://github.com/phalcon/phalcon/discussions"
  },
  {
    "label": "Blog",
    "link": "https://blog.phalcon.io/"
  }
];
