// Generated by resources/nimbus/convert.py from the mkdocs.yml nav of version 5.20. Do not edit.
export default [
  {
    "label": "Home",
    "collapsed": true,
    "items": [
      {
        "label": "Introduction",
        "link": "/5.20/introduction/"
      },
      {
        "label": "Changelog",
        "collapsed": true,
        "items": [
          {
            "label": "Current Version",
            "link": "https://github.com/phalcon/cphalcon/blob/5.0.x/CHANGELOG-5.0.md"
          },
          {
            "label": "Releases",
            "link": "/5.20/releases/"
          },
          {
            "label": "How to upgrade",
            "link": "/5.20/upgrade/"
          }
        ]
      },
      {
        "label": "Contributing",
        "collapsed": true,
        "items": [
          "contributions",
          "ai-development",
          {
            "label": "Asking a question",
            "link": "https://phalcon.io/discussions"
          },
          {
            "label": "Requesting a change",
            "link": "/5.20/new-feature-request/"
          },
          {
            "label": "Issuing a Pull Request",
            "link": "/5.20/new-pull-request/"
          }
        ]
      },
      {
        "label": "Guides",
        "collapsed": true,
        "items": [
          {
            "label": "Backtrace Generation",
            "link": "/5.20/generating-backtrace/"
          },
          "reproducible-tests",
          {
            "label": "Testing environment",
            "link": "/5.20/testing-environment/"
          },
          "talon",
          {
            "label": "Coding Standard",
            "link": "/5.20/coding-standard/"
          }
        ]
      },
      {
        "label": "Sponsoring",
        "link": "/5.20/sponsors/"
      }
    ]
  },
  {
    "label": "Getting Started",
    "collapsed": true,
    "items": [
      "installation",
      "webserver-setup",
      {
        "label": "Environments",
        "collapsed": true,
        "items": [
          "environments-devilbox",
          "environments-docker"
        ]
      },
      {
        "label": "Development Tools",
        "collapsed": true,
        "items": [
          {
            "label": "Devtools",
            "link": "/5.20/devtools/"
          },
          "quill",
          "support-debug",
          "debug-bar",
          "unit-testing"
        ]
      },
      {
        "label": "Tutorials",
        "collapsed": true,
        "items": [
          {
            "label": "Basic",
            "link": "/5.20/tutorial-basic/"
          },
          {
            "label": "Invo",
            "link": "/5.20/tutorial-invo/"
          },
          {
            "label": "REST",
            "link": "/5.20/tutorial-rest/"
          },
          {
            "label": "Vokuro",
            "link": "/5.20/tutorial-vokuro/"
          },
          {
            "label": "Vokuro ADR",
            "link": "/5.20/tutorial-vokuro-adr/"
          },
          {
            "label": "Use case",
            "link": "/5.20/use-case/"
          },
          "performance"
        ]
      }
    ]
  },
  {
    "label": "Core",
    "collapsed": true,
    "items": [
      "application",
      {
        "label": "Micro",
        "link": "/5.20/application-micro/"
      },
      {
        "label": "CLI",
        "link": "/5.20/application-cli/"
      },
      "container",
      {
        "label": "DI Container",
        "link": "/5.20/di/"
      },
      {
        "label": "MVC",
        "link": "/5.20/mvc/"
      },
      {
        "label": "ADR",
        "collapsed": true,
        "items": [
          {
            "label": "Overview",
            "link": "/5.20/adr/"
          },
          {
            "label": "Actions",
            "link": "/5.20/adr-actions/"
          },
          {
            "label": "Domain",
            "link": "/5.20/adr-domain/"
          },
          {
            "label": "Payload",
            "link": "/5.20/adr-payload/"
          },
          {
            "label": "Responders",
            "link": "/5.20/adr-responders/"
          },
          {
            "label": "Input",
            "link": "/5.20/adr-input/"
          },
          {
            "label": "Front Controller",
            "link": "/5.20/adr-front-controller/"
          },
          {
            "label": "Router",
            "link": "/5.20/adr-router/"
          },
          {
            "label": "Dispatcher",
            "link": "/5.20/adr-dispatcher/"
          },
          {
            "label": "Middleware",
            "link": "/5.20/adr-middleware/"
          },
          {
            "label": "Emitter",
            "link": "/5.20/adr-emitter/"
          },
          {
            "label": "Error Responder",
            "link": "/5.20/adr-error-responder/"
          },
          {
            "label": "Container",
            "link": "/5.20/adr-container/"
          },
          {
            "label": "Migrating from MVC",
            "link": "/5.20/mvc-to-adr/"
          }
        ]
      },
      "namespaces"
    ]
  },
  {
    "label": "Database",
    "collapsed": true,
    "items": [
      {
        "label": "Layer",
        "link": "/5.20/db-layer/"
      },
      {
        "label": "PHQL",
        "link": "/5.20/db-phql/"
      },
      {
        "label": "ODM",
        "link": "/5.20/db-odm/"
      },
      "db-models",
      {
        "label": "Behaviors",
        "link": "/5.20/db-models-behaviors/"
      },
      {
        "label": "Cache",
        "link": "/5.20/db-models-cache/"
      },
      {
        "label": "Events",
        "link": "/5.20/db-models-events/"
      },
      {
        "label": "Metadata",
        "link": "/5.20/db-models-metadata/"
      },
      {
        "label": "Relationships",
        "link": "/5.20/db-models-relationships/"
      },
      {
        "label": "Transactions",
        "link": "/5.20/db-models-transactions/"
      },
      {
        "label": "Validators",
        "link": "/5.20/db-models-validation/"
      },
      "db-pagination",
      {
        "label": "Migrations",
        "link": "/5.20/db-migrations/"
      },
      {
        "label": "DataMapper",
        "link": "/5.20/datamapper/"
      }
    ]
  },
  {
    "label": "Front End",
    "collapsed": true,
    "items": [
      {
        "label": "Assets",
        "link": "/5.20/assets/"
      },
      {
        "label": "Flash Messenger",
        "link": "/5.20/flash/"
      },
      "forms",
      "image",
      {
        "label": "HTML",
        "collapsed": true,
        "items": [
          {
            "label": "Attributes",
            "link": "/5.20/html-attributes/"
          },
          {
            "label": "Breadcrumbs",
            "link": "/5.20/html-breadcrumbs/"
          },
          "html-escaper",
          {
            "label": "Link",
            "link": "/5.20/html-link/"
          },
          "html-tagfactory"
        ]
      },
      {
        "label": "Tag (legacy)",
        "link": "/5.20/tag/"
      },
      {
        "label": "View",
        "link": "/5.20/views/"
      },
      {
        "label": "Volt",
        "link": "/5.20/volt/"
      }
    ]
  },
  {
    "label": "Business Logic",
    "collapsed": true,
    "items": [
      {
        "label": "Access Control Lists",
        "link": "/5.20/acl/"
      },
      "annotations",
      {
        "label": "Authentication",
        "link": "/5.20/auth/"
      },
      "controllers",
      {
        "label": "Dispatcher",
        "link": "/5.20/dispatcher/"
      },
      {
        "label": "Event Manager",
        "link": "/5.20/events/"
      },
      {
        "label": "Filters",
        "link": "/5.20/filter-filter/"
      },
      {
        "label": "Routing",
        "link": "/5.20/routing/"
      },
      {
        "label": "Sessions",
        "link": "/5.20/session/"
      },
      {
        "label": "Url",
        "link": "/5.20/mvc-url/"
      },
      {
        "label": "Validation",
        "link": "/5.20/filter-validation/"
      }
    ]
  },
  {
    "label": "Services",
    "collapsed": true,
    "items": [
      "cache",
      {
        "label": "Config",
        "link": "/5.20/config/"
      },
      "html-escaper",
      "autoload",
      "logger",
      {
        "label": "HTTP",
        "collapsed": true,
        "items": [
          {
            "label": "Cookies",
            "link": "/5.20/response/"
          },
          {
            "label": "Request",
            "link": "/5.20/request/"
          },
          {
            "label": "Response",
            "link": "/5.20/response/"
          }
        ]
      },
      {
        "label": "i18n",
        "collapsed": true,
        "items": [
          "i18n",
          {
            "label": "Translate",
            "link": "/5.20/translate/"
          }
        ]
      },
      {
        "label": "Queue",
        "link": "/5.20/queue/"
      },
      {
        "label": "Security",
        "collapsed": true,
        "items": [
          {
            "label": "Cryptography",
            "link": "/5.20/encryption-crypt/"
          },
          "encryption-security",
          {
            "label": "JWT",
            "link": "/5.20/encryption-security-jwt/"
          }
        ]
      },
      {
        "label": "Storage",
        "link": "/5.20/storage/"
      },
      {
        "label": "Utility",
        "collapsed": true,
        "items": [
          {
            "label": "Clock",
            "link": "/5.20/time-clock/"
          },
          "support-collection",
          "domain",
          "support-helper",
          {
            "label": "Registry",
            "link": "/5.20/support-registry/"
          },
          "support-settings",
          "traits",
          {
            "label": "Version",
            "link": "/5.20/support-version/"
          }
        ]
      }
    ]
  },
  {
    "label": "API",
    "link": "/5.20/api/"
  },
  {
    "label": "Discussions",
    "link": "https://github.com/orgs/phalcon/discussions"
  },
  {
    "label": "Discussions(v6)",
    "link": "https://github.com/phalcon/phalcon/discussions"
  },
  {
    "label": "Blog",
    "link": "https://blog.phalcon.io/"
  }
];
