// Generated by resources/nimbus/convert.py from the mkdocs.yml nav of version 5.5. Do not edit.
export default [
  {
    "label": "Home",
    "collapsed": true,
    "items": [
      {
        "label": "Introduction",
        "link": "/5.5/introduction/"
      },
      {
        "label": "Changelog",
        "collapsed": true,
        "items": [
          {
            "label": "Current Version",
            "link": "https://github.com/phalcon/cphalcon/blob/5.0.x/CHANGELOG-5.0.md"
          },
          {
            "label": "Releases",
            "link": "/5.5/releases/"
          },
          {
            "label": "How to upgrade",
            "link": "/5.5/upgrade/"
          }
        ]
      },
      {
        "label": "Contributing",
        "collapsed": true,
        "items": [
          "contributions",
          {
            "label": "Asking a question",
            "link": "https://phalcon.io/discussions"
          },
          {
            "label": "Requesting a change",
            "link": "/5.5/new-feature-request/"
          },
          {
            "label": "Issuing a Pull Request",
            "link": "/5.5/new-pull-request/"
          }
        ]
      },
      {
        "label": "Guides",
        "collapsed": true,
        "items": [
          {
            "label": "Backtrace Generation",
            "link": "/5.5/generating-backtrace/"
          },
          "reproducible-tests",
          {
            "label": "Testing environment",
            "link": "/5.5/testing-environment/"
          },
          {
            "label": "Coding Standard",
            "link": "/5.5/coding-standard/"
          }
        ]
      },
      {
        "label": "Sponsoring",
        "link": "/5.5/sponsors/"
      }
    ]
  },
  {
    "label": "Getting Started",
    "collapsed": true,
    "items": [
      "installation",
      "webserver-setup",
      {
        "label": "Environments",
        "collapsed": true,
        "items": [
          {
            "label": "Devilbox",
            "link": "/5.5/environments-devilbox/"
          },
          {
            "label": "Nanobox",
            "link": "/5.5/environments-nanobox/"
          }
        ]
      },
      {
        "label": "Development Tools",
        "collapsed": true,
        "items": [
          {
            "label": "Devtools",
            "link": "/5.5/devtools/"
          },
          "support-debug",
          {
            "label": "Migrations",
            "link": "/5.5/db-migrations/"
          },
          "unit-testing"
        ]
      },
      {
        "label": "Tutorials",
        "collapsed": true,
        "items": [
          {
            "label": "Basic",
            "link": "/5.5/tutorial-basic/"
          },
          {
            "label": "Invo",
            "link": "/5.5/tutorial-invo/"
          },
          {
            "label": "REST",
            "link": "/5.5/tutorial-rest/"
          },
          {
            "label": "Vokuro",
            "link": "/5.5/tutorial-vokuro/"
          },
          {
            "label": "Use case",
            "link": "/5.5/use-case/"
          },
          "performance"
        ]
      }
    ]
  },
  {
    "label": "Core",
    "collapsed": true,
    "items": [
      "application",
      {
        "label": "Micro",
        "link": "/5.5/application-micro/"
      },
      {
        "label": "CLI",
        "link": "/5.5/application-cli/"
      },
      {
        "label": "DI Container",
        "link": "/5.5/di/"
      },
      {
        "label": "MVC",
        "link": "/5.5/mvc/"
      },
      "namespaces"
    ]
  },
  {
    "label": "Database",
    "collapsed": true,
    "items": [
      {
        "label": "Layer",
        "link": "/5.5/db-layer/"
      },
      {
        "label": "PHQL",
        "link": "/5.5/db-phql/"
      },
      {
        "label": "ODM",
        "link": "/5.5/db-odm/"
      },
      "db-models",
      {
        "label": "Behaviors",
        "link": "/5.5/db-models-behaviors/"
      },
      {
        "label": "Cache",
        "link": "/5.5/db-models-cache/"
      },
      {
        "label": "Events",
        "link": "/5.5/db-models-events/"
      },
      {
        "label": "Metadata",
        "link": "/5.5/db-models-metadata/"
      },
      {
        "label": "Relationships",
        "link": "/5.5/db-models-relationships/"
      },
      {
        "label": "Transactions",
        "link": "/5.5/db-models-transactions/"
      },
      {
        "label": "Validators",
        "link": "/5.5/db-models-validation/"
      },
      "db-pagination",
      {
        "label": "Migrations",
        "link": "/5.5/db-migrations/"
      },
      {
        "label": "DataMapper",
        "link": "/5.5/datamapper/"
      }
    ]
  },
  {
    "label": "Front End",
    "collapsed": true,
    "items": [
      {
        "label": "Assets",
        "link": "/5.5/assets/"
      },
      {
        "label": "Flash Messenger",
        "link": "/5.5/flash/"
      },
      "forms",
      "image",
      {
        "label": "HTML",
        "collapsed": true,
        "items": [
          {
            "label": "Attributes",
            "link": "/5.5/html-attributes/"
          },
          {
            "label": "Breadcrumbs",
            "link": "/5.5/html-breadcrumbs/"
          },
          "html-escaper",
          {
            "label": "Link",
            "link": "/5.5/html-link/"
          },
          "html-tagfactory"
        ]
      },
      {
        "label": "Tag (legacy)",
        "link": "/5.5/tag/"
      },
      {
        "label": "View",
        "link": "/5.5/views/"
      },
      {
        "label": "Volt",
        "link": "/5.5/volt/"
      }
    ]
  },
  {
    "label": "Business Logic",
    "collapsed": true,
    "items": [
      {
        "label": "Access Control Lists",
        "link": "/5.5/acl/"
      },
      "annotations",
      "controllers",
      {
        "label": "Dispatcher",
        "link": "/5.5/dispatcher/"
      },
      {
        "label": "Event Manager",
        "link": "/5.5/events/"
      },
      {
        "label": "Filters",
        "link": "/5.5/filter-filter/"
      },
      {
        "label": "Routing",
        "link": "/5.5/routing/"
      },
      {
        "label": "Sessions",
        "link": "/5.5/session/"
      },
      {
        "label": "Url",
        "link": "/5.5/mvc-url/"
      },
      {
        "label": "Validation",
        "link": "/5.5/filter-validation/"
      }
    ]
  },
  {
    "label": "Services",
    "collapsed": true,
    "items": [
      "cache",
      {
        "label": "Config",
        "link": "/5.5/config/"
      },
      "html-escaper",
      "autoload",
      "logger",
      {
        "label": "HTTP",
        "collapsed": true,
        "items": [
          {
            "label": "Cookies",
            "link": "response#cookies"
          },
          {
            "label": "Request",
            "link": "/5.5/request/"
          },
          {
            "label": "Response",
            "link": "/5.5/response/"
          }
        ]
      },
      {
        "label": "i18n",
        "collapsed": true,
        "items": [
          "i18n",
          {
            "label": "Translate",
            "link": "/5.5/translate/"
          }
        ]
      },
      {
        "label": "Queue",
        "link": "/5.5/queue/"
      },
      {
        "label": "Security",
        "collapsed": true,
        "items": [
          {
            "label": "Cryptography",
            "link": "/5.5/encryption-crypt/"
          },
          "encryption-security",
          {
            "label": "JWT",
            "link": "/5.5/encryption-security-jwt/"
          }
        ]
      },
      {
        "label": "Storage",
        "link": "/5.5/storage/"
      },
      {
        "label": "Utility",
        "collapsed": true,
        "items": [
          "support-collection",
          "domain",
          "support-helper",
          {
            "label": "Registry",
            "link": "/5.5/support-registry/"
          },
          {
            "label": "Version",
            "link": "/5.5/support-version/"
          }
        ]
      }
    ]
  },
  {
    "label": "API",
    "link": "/5.5/api/"
  },
  {
    "label": "Discussions",
    "link": "https://github.com/orgs/phalcon/discussions"
  },
  {
    "label": "Discussions(v6)",
    "link": "https://github.com/phalcon/phalcon/discussions"
  },
  {
    "label": "Blog",
    "link": "https://blog.phalcon.io/"
  }
];
