// Generated by resources/nimbus/convert.py from the MkDocs redirect stubs of version 5.16. Do not edit.
export default {
  "/5.16/collection/": "/5.16/support-collection/",
  "/5.16/helper/": "/5.16/support-helper/",
  "/5.16/http-factories/": "/5.16/request/",
  "/5.16/http-request/": "/5.16/request/",
  "/5.16/http-response/": "/5.16/request/",
  "/5.16/http-server-request/": "/5.16/request/",
  "/5.16/http-stream/": "/5.16/request/",
  "/5.16/http-uploaded-file/": "/5.16/request/",
  "/5.16/http-uri/": "/5.16/request/",
  "/5.16/": "/5.16/introduction/",
  "/5.16/loader/": "/5.16/autoload/",
  "/5.16/migrations/": "/5.16/db-migrations/",
  "/5.16/registry/": "/5.16/support-registry/",
  "/5.16/version/": "/5.16/support-version/"
};
