// Generated by resources/nimbus/convert.py from the MkDocs redirect stubs of version 5.17. Do not edit.
export default {
  "/5.17/collection/": "/5.17/support-collection/",
  "/5.17/helper/": "/5.17/support-helper/",
  "/5.17/http-factories/": "/5.17/request/",
  "/5.17/http-request/": "/5.17/request/",
  "/5.17/http-response/": "/5.17/request/",
  "/5.17/http-server-request/": "/5.17/request/",
  "/5.17/http-stream/": "/5.17/request/",
  "/5.17/http-uploaded-file/": "/5.17/request/",
  "/5.17/http-uri/": "/5.17/request/",
  "/5.17/": "/5.17/introduction/",
  "/5.17/loader/": "/5.17/autoload/",
  "/5.17/migrations/": "/5.17/db-migrations/",
  "/5.17/registry/": "/5.17/support-registry/",
  "/5.17/version/": "/5.17/support-version/"
};
