// Generated by resources/nimbus/convert.py from the MkDocs redirect stubs of version 5.18. Do not edit.
export default {
  "/5.18/collection/": "/5.18/support-collection/",
  "/5.18/helper/": "/5.18/support-helper/",
  "/5.18/http-factories/": "/5.18/request/",
  "/5.18/http-request/": "/5.18/request/",
  "/5.18/http-response/": "/5.18/request/",
  "/5.18/http-server-request/": "/5.18/request/",
  "/5.18/http-stream/": "/5.18/request/",
  "/5.18/http-uploaded-file/": "/5.18/request/",
  "/5.18/http-uri/": "/5.18/request/",
  "/5.18/": "/5.18/introduction/",
  "/5.18/loader/": "/5.18/autoload/",
  "/5.18/migrations/": "/5.18/db-migrations/",
  "/5.18/registry/": "/5.18/support-registry/",
  "/5.18/version/": "/5.18/support-version/"
};
