// Generated by resources/nimbus/convert.py from the MkDocs redirect stubs of version 5.19. Do not edit.
export default {
  "/5.19/collection/": "/5.19/support-collection/",
  "/5.19/helper/": "/5.19/support-helper/",
  "/5.19/http-factories/": "/5.19/request/",
  "/5.19/http-request/": "/5.19/request/",
  "/5.19/http-response/": "/5.19/request/",
  "/5.19/http-server-request/": "/5.19/request/",
  "/5.19/http-stream/": "/5.19/request/",
  "/5.19/http-uploaded-file/": "/5.19/request/",
  "/5.19/http-uri/": "/5.19/request/",
  "/5.19/": "/5.19/introduction/",
  "/5.19/loader/": "/5.19/autoload/",
  "/5.19/migrations/": "/5.19/db-migrations/",
  "/5.19/registry/": "/5.19/support-registry/",
  "/5.19/version/": "/5.19/support-version/"
};
