// Generated by resources/nimbus/convert.py from the MkDocs redirect stubs of version 5.20. Do not edit.
export default {
  "/5.20/collection/": "/5.20/support-collection/",
  "/5.20/helper/": "/5.20/support-helper/",
  "/5.20/http-factories/": "/5.20/request/",
  "/5.20/http-request/": "/5.20/request/",
  "/5.20/http-response/": "/5.20/request/",
  "/5.20/http-server-request/": "/5.20/request/",
  "/5.20/http-stream/": "/5.20/request/",
  "/5.20/http-uploaded-file/": "/5.20/request/",
  "/5.20/http-uri/": "/5.20/request/",
  "/5.20/": "/5.20/introduction/",
  "/5.20/loader/": "/5.20/autoload/",
  "/5.20/migrations/": "/5.20/db-migrations/",
  "/5.20/registry/": "/5.20/support-registry/",
  "/5.20/version/": "/5.20/support-version/"
};
