// Generated by resources/nimbus/convert.py from the MkDocs redirect stubs of version 5.21. Do not edit.
export default {
  "/5.21/collection/": "/5.21/support-collection/",
  "/5.21/helper/": "/5.21/support-helper/",
  "/5.21/http-factories/": "/5.21/request/",
  "/5.21/http-request/": "/5.21/request/",
  "/5.21/http-response/": "/5.21/request/",
  "/5.21/http-server-request/": "/5.21/request/",
  "/5.21/http-stream/": "/5.21/request/",
  "/5.21/http-uploaded-file/": "/5.21/request/",
  "/5.21/http-uri/": "/5.21/request/",
  "/5.21/": "/5.21/introduction/",
  "/5.21/loader/": "/5.21/autoload/",
  "/5.21/migrations/": "/5.21/db-migrations/",
  "/5.21/registry/": "/5.21/support-registry/",
  "/5.21/version/": "/5.21/support-version/"
};
