// Generated by resources/nimbus/convert.py from the MkDocs redirect stubs of version 5.22. Do not edit.
export default {
  "/5.22/collection/": "/5.22/support-collection/",
  "/5.22/helper/": "/5.22/support-helper/",
  "/5.22/http-factories/": "/5.22/request/",
  "/5.22/http-request/": "/5.22/request/",
  "/5.22/http-response/": "/5.22/request/",
  "/5.22/http-server-request/": "/5.22/request/",
  "/5.22/http-stream/": "/5.22/request/",
  "/5.22/http-uploaded-file/": "/5.22/request/",
  "/5.22/http-uri/": "/5.22/request/",
  "/5.22/": "/5.22/introduction/",
  "/5.22/loader/": "/5.22/autoload/",
  "/5.22/migrations/": "/5.22/db-migrations/",
  "/5.22/registry/": "/5.22/support-registry/",
  "/5.22/version/": "/5.22/support-version/"
};
