// Generated by resources/nimbus/convert.py from the MkDocs redirect stubs of version 6.0. Do not edit.
export default {
  "/6.0/collection/": "/6.0/support-collection/",
  "/6.0/helper/": "/6.0/support-helper/",
  "/6.0/http-factories/": "/6.0/request/",
  "/6.0/http-request/": "/6.0/request/",
  "/6.0/http-response/": "/6.0/request/",
  "/6.0/http-server-request/": "/6.0/request/",
  "/6.0/http-stream/": "/6.0/request/",
  "/6.0/http-uploaded-file/": "/6.0/request/",
  "/6.0/http-uri/": "/6.0/request/",
  "/6.0/": "/6.0/introduction/",
  "/6.0/loader/": "/6.0/autoload/",
  "/6.0/migrations/": "/6.0/db-migrations/",
  "/6.0/registry/": "/6.0/support-registry/",
  "/6.0/version/": "/6.0/support-version/"
};
