import { defineCollection } from "astro:content";
import { z } from "astro/zod";
import { docsCollection, partialsCollection } from "@cloudflare/nimbus-docs/content";

// Generated by resources/nimbus/convert.py --register from src/content/docs-*.
// Do not edit. The primary `docs` collection stays empty: every version
// lives in its own `docs-<version>` collection.
const schemaFields = { audience: z.literal("human").optional() };

export const collections = {
  docs: defineCollection(docsCollection({ schemaFields })),
  "docs-6.0": defineCollection(docsCollection({ base: "docs-6.0", schemaFields })),
  "docs-5.20": defineCollection(docsCollection({ base: "docs-5.20", schemaFields })),
  "docs-5.19": defineCollection(docsCollection({ base: "docs-5.19", schemaFields })),
  "docs-5.18": defineCollection(docsCollection({ base: "docs-5.18", schemaFields })),
  "docs-5.17": defineCollection(docsCollection({ base: "docs-5.17", schemaFields })),
  "docs-5.16": defineCollection(docsCollection({ base: "docs-5.16", schemaFields })),
  "docs-5.15": defineCollection(docsCollection({ base: "docs-5.15", schemaFields })),
  "docs-5.14": defineCollection(docsCollection({ base: "docs-5.14", schemaFields })),
  "docs-5.13": defineCollection(docsCollection({ base: "docs-5.13", schemaFields })),
  "docs-5.12": defineCollection(docsCollection({ base: "docs-5.12", schemaFields })),
  "docs-5.11": defineCollection(docsCollection({ base: "docs-5.11", schemaFields })),
  "docs-5.9": defineCollection(docsCollection({ base: "docs-5.9", schemaFields })),
  "docs-5.8": defineCollection(docsCollection({ base: "docs-5.8", schemaFields })),
  "docs-5.7": defineCollection(docsCollection({ base: "docs-5.7", schemaFields })),
  "docs-5.6": defineCollection(docsCollection({ base: "docs-5.6", schemaFields })),
  "docs-5.5": defineCollection(docsCollection({ base: "docs-5.5", schemaFields })),
  "docs-5.4": defineCollection(docsCollection({ base: "docs-5.4", schemaFields })),
  "docs-4.2": defineCollection(docsCollection({ base: "docs-4.2", schemaFields })),
  "docs-3.4": defineCollection(docsCollection({ base: "docs-3.4", schemaFields })),
  partials: defineCollection(partialsCollection()),
};
