---
// Generated by resources/nimbus/convert.py --register from
// resources/nimbus/templates/slug.astro. Do not edit; change the template.
import DocsLayout from "../../layouts/DocsLayout.astro";
import {
  getCollectionStaticPaths,
  getCollectionPageProps,
  getIndexedEntries,
  getPrevNext,
  getBreadcrumbs,
  getEditUrl,
  getLastUpdated,
  getRouteFlags,
  getTOC,
} from "@cloudflare/nimbus-docs";
import { components } from "../../components";
import { versionBanner } from "../../lib/site.mjs";
import { buildVersionSidebar } from "../../lib/version-sidebar.mjs";
import { sidebars } from "../../versions.generated.mjs";

const VERSION = "__VERSION__";

export const prerender = true;
export const getStaticPaths = getCollectionStaticPaths("docs-__VERSION__");

const { entry, Content, headings } = await getCollectionPageProps<"docs-__VERSION__">(Astro);

const currentSlug = Astro.url.pathname.replace(/\/$/, "") || "/";
const { sidebar: sidebarOn, tableOfContents: tocOn } = await getRouteFlags(entry);

// The rail is this version's own navigation, built from the pages the
// version has (see src/lib/version-sidebar.mjs).
const indexed = (await getIndexedEntries()).filter((item) => item.collection === entry.collection);
const sidebar = sidebarOn ? buildVersionSidebar(sidebars[VERSION], indexed, currentSlug) : false;
const prevNext = await getPrevNext(currentSlug, {
  sidebarTree: sidebar === false ? [] : sidebar,
  overrides: { prev: entry.data.prev, next: entry.data.next },
});
// Pass the collection so breadcrumbs resolve against this version, not the
// empty primary collection.
const breadcrumbs = await getBreadcrumbs(currentSlug, { collection: entry.collection });
const editUrl = await getEditUrl(entry);
const lastUpdated = entry.data.lastUpdated ?? await getLastUpdated(entry);
const tocConfig = entry.data.tableOfContents;
const toc = tocOn && tocConfig !== false ? getTOC(headings, tocConfig) : false;
const markdownPath = `/${VERSION}/${entry.id}/index.md`;
const markdownUrl = Astro.site ? new URL(markdownPath, Astro.site).href : markdownPath;
const socialImage = entry.data.socialImage ?? `/og/${VERSION}/${entry.id}.png`;
// A page of a non-stable version carries the version banner unless the
// page sets its own (STABLE_VERSIONS and PRERELEASES in src/lib/site.mjs).
const banner = entry.data.banner ?? versionBanner(VERSION) ?? undefined;
---

<DocsLayout
  title={entry.data.title}
  description={entry.data.description}
  sidebar={sidebar}
  headings={toc}
  breadcrumbs={breadcrumbs}
  prevNext={prevNext}
  mode={entry.data.mode}
  banner={banner}
  head={entry.data.head}
  searchable={entry.data.searchable}
  noindex={entry.data.noindex}
  markdownUrl={markdownUrl}
  socialImage={socialImage}
  lastUpdated={lastUpdated}
  editUrl={editUrl}
  draft={entry.data.draft}
  audience={entry.data.audience}
  collection={entry.collection}
  entryId={entry.id}
>
  <Content components={components} />
</DocsLayout>
